name: Pipeline generator
on:
  - push
  - pull_request
permissions: write-all
jobs:
  run-generator:
    runs-on: ubuntu-latest
    outputs:
      workflow-updated: ${{ steps.run-action.outputs.workflow-updated }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: "false"
      - name: Run pipeline-gen action
        id: run-action
        uses: GitHub-Accelerate/automatic-pipeline-generator-action@main
        env:
          GH_WORKFLOW_WRITE: ${{ secrets.GH_WORKFLOW_WRITE }}
  main:
    runs-on: ubuntu-latest
    needs: run-generator
    if: needs.run-generator.outputs.workflow-updated == 'false'
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: 1.25.3
      - name: Build
        run: make build
      - name: Test
        run: make test
      - name: Package build folder
        run: |
          zip -r build.zip ../build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build.zip
